### PR TITLE
[WIP] chore: Add workflows, update README

### LINKED ISSUE #1: Bring moogle inline with our other repos
## Summary

What:

Bring the readme in line with the content of our other repositories, as well as workflows

Why:

Consistency

### PR DESCRIPTION
**Pull request by ebebbington**
Fixes #1 

## Summary

* Brings workflows and README inline with rest of the org

## TODO

- [x] `<script src="https://unpkg.com/@drashland/moogle@0.0.1-alpha-6"></script>` doesn't work
- [x] ~~Add tests to ensure the above does work if possible~~
- [ ] There is a lot of ci jobs, maybe we could target latest of node?

### CODE REVIEW

**Comment by ebebbington** [comment]
TODO: Doesnt seem like `<script src="https://unpkg.com/@drashland/moogle@0.0.1-alpha-6"></script>` works

**Comment by ebebbington** [comment]
using https://unpkg.com/@drashland/moogle@0.0.1-alpha-6 doesn't seem to work

**Comment by Guergeiro** [comment]
> using https://unpkg.com/@drashland/moogle@0.0.1-alpha-6 doesn't seem to work

The reason is that that version was not published to npm since the workflow failed. That's why this is still "alpha", because if failing release all over the place.

[0.0.1-alpha-1](https://unpkg.com/@drashland/moogle@0.0.1-alpha-1/lib/Moogle.js) was the last one that I was able to publish.

**Comment by Guergeiro** [comment]
One can also use [jsdelivery](https://cdn.jsdelivr.net/npm/@drashland/moogle@0.0.1-alpha-1/lib/Moogle.min.js)

**Comment by ebebbington** [comment]
Alright I’ll try check it with specifying then alpha 1 version

**Comment by Guergeiro** [comment]
Btw, the `README.md` stopped having syntax highlighting. Is it because of the extra spaces added?

**Comment by ebebbington** [comment]
> Btw, the `README.md` stopped having syntax highlighting. Is it because of the extra spaces added?

yeah i guess so - seems like a bug with deno fmt, but ill just 'unindent' it lol

**Comment by ebebbington** [comment]
good catch!

**Comment by ebebbington** [comment]
Using alpha 1 as the release, using moogle from the browser does work

**Comment by Guergeiro** [comment]
That's why I had the formatter only working on `./src`. Maybe we could be specific about the directories/files?

**Comment by ebebbington** [comment]
> That's why I had the formatter only working on `./src`. Maybe we could be specific about the directories/files?

it's all good now, i think it's just cause the code blocks were indented **and** using `\`\`\``

**Comment by Guergeiro** [comment]
As for the node tests, I followed the ones that still are not [EOL](https://nodejs.org/en/about/releases/), but we could just as well just test on Active LTS and Current.

**Review by Guergeiro — APPROVED** [review]
Let's GO!

**Pull request merged**
